version: '3.8'

services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: TESTE123
      MYSQL_DATABASE: clients
      MYSQL_USER: root
      MYSQL_PASSWORD: TESTE123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
